### ISSUE TITLE
Outline and Info color for cesium

### ISSUE THREAD

**Issue by DrYSG** [spatialillusions/milsymbol#140]
I really like this project. But I am having issues getting anything other than information text in anything other than black text, and I want the direction array (and probably also the outline) in something other than a 1px black line. Right now, the black defaults are not clearly visible when using bing sattelite maps as the cesium base map.

Here is the my code as it stands (Chrome V61).

```

        makeGlyph(sprite) {
        let milSym = milSymbols[sprite.type]
        if (milSym === undefined) milSym = milSymbols["UFO"]
        sprite.mps = 0
        sprite.symbol = milSym
        let sym2 = new ms.Symbol(milSym, { size: 26, type: sprite.marking, speed: sprite.mps + ' mps', direction: sprite.heading, infoColor: "red" })
        let glyph = new Cesium.Entity({
            name: sprite.marking,
            id: sprite.id,
            position: Cesium.Cartesian3.fromDegrees(sprite.lon, sprite.lat, sprite.altitude),
            billboard: {
                image: sym2.asCanvas(), //Get the canvas for the billboard
                // heightReference : Cesium.HeightReference.CLAMP_TO_GROUND,
                pixelOffset: new Cesium.Cartesian2(-sym2.markerAnchor.x, -sym2.markerAnchor.y), // Symbol offset
                eyeOffset: new Cesium.Cartesian3(0.0, 0.0, 0.0), // default
                horizontalOrigin: Cesium.HorizontalOrigin.LEFT, // default
                verticalOrigin: Cesium.VerticalOrigin.TOP
            },
            path: {
                leadTime: 100,
                trailTime: 100,
                width: 1,
                material: new Cesium.ColorMaterialProperty({
                    color : Cesium.Color.ORANGE,
                })
            },
            label: {
                text: sprite.marking,
                font: '14pt monospace',
                style: Cesium.LabelStyle.FILL_AND_OUTLINE,
                outlineWidth: 1,
                verticalOrigin: Cesium.VerticalOrigin.BOTTOM,
                pixelOffset: new Cesium.Cartesian2(0, -20)
            }
        })
        sprite.glyph = glyph
        this.infoBox(sprite)
        this.viewer.entities.add(glyph)
    }
    updateGlyph(sprite) {
        this.viewer.entities.suspendEvents()
        let loc = Cesium.Cartesian3.fromDegrees(sprite.lon, sprite.lat, sprite.altitude)
        sprite.mps = sprite.speed[0] + sprite.speed[1] + sprite.speed[2]
        sprite.glyph.position = loc;
        this.infoBox(sprite)
        this.viewer.entities.resumeEvents()
    }
```

**Comment by spatialillusions** [comment]
The infoColor setting is a bug that was fixed the other day in #138, if you download the master branch it is fixed, but I haven't released a new version with this fix yet. 

To get the information to stand out more I would suggest setting outlineWidth to a number such as 3 or 4, to get an outline around the symbol. It would also be possible to change the color of the direction arrow with some setting or as an extension.

**Comment by spatialillusions** [comment]
I have been thinking and it would be possible to add an option called outlineColor that would affect the outline of the symbol frame, the direction arrow and the echelon indicators if set. What do you think about that? 

Otherwise I would at the moment change update your code to use the outlineWidth option to have an outline around all parts of the generated symbol. Like this:
```js 
makeGlyph(sprite) {
  let milSym = milSymbols[sprite.type];
  if (milSym === undefined) milSym = milSymbols["UFO"];
  sprite.mps = 0;
  sprite.symbol = milSym;
  let sym2 = new ms.Symbol(
    milSym,
    { // Properties object
      type: sprite.marking,
      speed: sprite.mps + " mps",
      direction: sprite.heading
    },
    { // Style object
      outlineWidth: 4,
      size: 26
      /*infoColor: "red"*/
    }
  );
  let glyph = new Cesium.Entity({
    name: sprite.marking,
    id: sprite.id,
    position: Cesium.Cartesian3.fromDegrees(
      sprite.lon,
      sprite.lat,
      sprite.altitude
    ),
    billboard: {
      image: sym2.asCanvas(), //Get the canvas for the billboard
      // heightReference : Cesium.HeightReference.CLAMP_TO_GROUND,
      pixelOffset: new Cesium.Cartesian2(
        -sym2.getAnchor().x,
        -sym2.getAnchor().y
      ), // Symbol offset
      eyeOffset: new Cesium.Cartesian3(0.0, 0.0, 0.0), // default
      horizontalOrigin: Cesium.HorizontalOrigin.LEFT, // default
      verticalOrigin: Cesium.VerticalOrigin.TOP
    },
    path: {
      leadTime: 100,
      trailTime: 100,
      width: 1,
      material: new Cesium.ColorMaterialProperty({
        color: Cesium.Color.ORANGE
      })
    },
    label: {
      text: sprite.marking,
      font: "14pt monospace",
      style: Cesium.LabelStyle.FILL_AND_OUTLINE,
      outlineWidth: 1,
      verticalOrigin: Cesium.VerticalOrigin.BOTTOM,
      pixelOffset: new Cesium.Cartesian2(0, -20)
    }
  });
  sprite.glyph = glyph;
  this.infoBox(sprite);
  this.viewer.entities.add(glyph);
}
updateGlyph(sprite) {
  this.viewer.entities.suspendEvents();
  let loc = Cesium.Cartesian3.fromDegrees(
    sprite.lon,
    sprite.lat,
    sprite.altitude
  );
  sprite.mps = sprite.speed[0] + sprite.speed[1] + sprite.speed[2];
  sprite.glyph.position = loc;
  this.infoBox(sprite);
  this.viewer.entities.resumeEvents();
}

```

**Comment by DrYSG** [comment]
Do you mind pushing this change (infoColor fix)  to NPM and giving it the version number 1.3.2 ? Thank you for the tip about the outlineWidth, but it seems to effect the legibility of the symbol info (see below).

I think the color option for the outline would help, since I could do some simulated glow around the symbol and the text (I realize that outline is crisp, and not a gradient, but then a real gradient is probably too cpu/gpu intensive for lots of symbols.

![capture](https://user-images.githubusercontent.com/2865368/32734474-24968760-c860-11e7-9a49-b4f3c1fc59e9.PNG)

**Comment by spatialillusions** [comment]
I have now released milsymbol 1.3.2, so now the infoColor option should work again.

**Comment by DrYSG** [comment]
I installed this, but I still get the black text for info. Also, as you can see from the image above, the outline does not make the  info text readable, more like the other way.

My main goal will be the direction arrow, but that needs to be time variant, so maybe not.

**Comment by spatialillusions** [comment]
Sorry, missed an error in the testing so the patch that I thought fixed the infoColor bug didn't work, will release a patched version in a few hours. 
When it comes to the outline that has something to do with how cesium draws billboards, they get distorted in some way.

**Comment by DrYSG** [comment]
Bitte shon, No reason to apologize. I am so pleased you did this and maintain it. I can only glimpse at how much work it is. 

In my humble opinion it is the way that SVG creates an outline, not the conversion to a Canvas, and now how Cesium shows the Canvas as a billboard (I turned off anti-alias and so it is always actual pixels with the normal to the viewer). But creating an outline around text does not really work well without good anti-alias and gradients. So one is stuck one way or the other. Color  lines will help since the key thing I want is the direction arrow, the rest I can show in the billboard label.

**Comment by spatialillusions** [comment]
Now, I keep my fingers crossed, milsymbol 1.3.3 should fix the problems. It also includes an updated unit generator in the examples folder where you can try out all the options. 

*Regarding your humble opinion, milsymbol dosen't convert SVG to Canvas, it uses SVG like instructions internally, but they are not quite SVG, they are then converted to SVG or pure Canvas draw instructions when the symbol is requested. The reason for this is that you otherwise might end up with a "tainted" canvas in some webbrowsers, and this will prevent the application to interact with the Canvas because of security reasons.
I think the reason that the icons look strange is that cesium dosen't pixel align the rasters when they put them on their atlas, and this could be connected to #142. Unfortunately I haven't had time to investigate further what the reason is and if it would be possible to solve in some way on my side. It gets better if you turn up the resolution of the icons, but it won't go away.*

**Comment by DrYSG** [comment]
Not asking you to spend time exploring this. But just to tell, what is going on, I am converting the symbol to a canvas manually, as suggested in the Cesium Milsymbols tutorial you wrote: https://cesium.com/blog/2016/07/20/cesium-and-milsymbol/

    image: sym2.asCanvas(), //Get the canvas for the billboard

And as suggested in: https://stackoverflow.com/questions/33784256/cesium-label-blurred

I have turned off anti-aliasing in cesium using:

        this.viewer.scene.fxaa = false // no anti-alias, otherwise billboards are blurry
