### ISSUE TITLE
69+ errors found in the code.

### ISSUE THREAD

**Issue by alexispolak** [spatialillusions/milsymbol#36]
Hi there @spatialillusions , i try to use this library for a tiny project in Unity3D but i found that is full of bugs. A lot of ";" missing and a lot of erros on the syntax. I start correcting a few but there are a LOT. Here is the modify milsymbol.js. Unity3d (i'm using MonoDevelop 5.9.6) compiler is BOO, it say that the next errors are in the next lines:
```
(206,26): BCE0044: expecting (, found 'text'.
(206,35): UCE0001: ';' expected. Insert a semicolon at the end.
(226,26): BCE0044: expecting (, found 'textm1'.
(226,37): UCE0001: ';' expected. Insert a semicolon at the end.
(237,26): BCE0044: expecting (, found 'textm2'.
(237,37): UCE0001: ';' expected. Insert a semicolon at the end.
(269,177): BCE0043: Unexpected token: ,.
(269,178): UCE0001: ';' expected. Insert a semicolon at the end.
(269,179): BCE0043: Unexpected token: type.
(269,184): BCE0043: Unexpected token: path.
```
and the list goes on...

PS: i can't upload the complete milsymbol.js modify, if you are interested i send it to your email.

**Comment by spatialillusions** [comment]
Thank you for the heads up, I will look into this during the weekend and remove as many errors as possible. I'll get back to you once it is done. 

/Måns

**Comment by spatialillusions** [comment]
I have now updated the code and removed almost all warnings and made some other minor code changes. Can you try out the latest version in the master branch and tell me if that works for you? Also really curious about what you are building in Unity.

**Comment by alexispolak** [comment]
Hey ! Thanks a lot for the rapid response. The project it's for georeferencing (don't know if i say it right in english) this units in AR. It's like a test project. As soon as i open the code, give me 4 errors. 
![errors](https://cloud.githubusercontent.com/assets/13720763/13351371/fb2919a8-dc64-11e5-91a3-19e45c2eb8e9.png)

But when i remove them, the compiler give me 26 more.
![errors2](https://cloud.githubusercontent.com/assets/13720763/13351439/69a911a8-dc65-11e5-847e-ed8732572195.png)
![errors3](https://cloud.githubusercontent.com/assets/13720763/13351463/8b55724c-dc65-11e5-9686-28695a3c3617.png)

I'm not really familiar with .js nor github but i will try to fixe some things if i have time in the weekend.

**Comment by spatialillusions** [comment]
Make sure you download the master branch, all missing semicolons and similar stuff should be fixed there, I haven't made a new release yet and will have to do some more testing before I do so. There is still some warnings if you are using jshint to validate the file, but they should be considered warnings and not errors. I haven't used unity to run my code so I can't really help you there, my main goal is to get it working in as many web browsers as possible and I'm not sure what unity is using to interpreter the code.

**Comment by alexispolak** [comment]
I redownload the master branch, and still getting the same erros from the las 3 screenshots. Unity compile the js with BOO (Link[http://answers.unity3d.com/questions/723812/what-are-the-javascript-compiler-errors.html](url) . 
Maybe if you have a few minutes, you can download Unity3d from the official website, create a new project and in there, in the Asset folder create a Plugin folder. If you put the .js in that folder, all the errors will pop up. Thanks a lot for all the good vibes !

**Comment by spatialillusions** [comment]
I think this might explain why the code isn't working in unity, and that there would be quite a large thing to make it work. But since milsymbol even has been ported to c++ I guess it's doable, but it's not anything I'm planning to do. 

http://wiki.unity3d.com/index.php?title=UnityScript_versus_JavaScript
